version: "3.8"

services:
  server:
    image: 'nginx:stable-alpine'
    ports:
     - '8080:80'
    volumes :
      - ./src:/var/www/html
      - ./nginx/certServer.crt:/etc/nginx/certs/certServer.crt
      - ./nginx/serverkey.pem:/etc/nginx/certs/serverkey.pem
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
      - mysql
  php:
    build:
      context: ./dockerfiles
      dockerfile: php.dockerfile
    volumes:
     - ./src:/var/www/html:delegated
     - ./src/php.ini://usr/local/etc/php/php.ini
    env_file:
    - ./env/php.env
  mysql:
   platform: linux/x86_64 
   image: mysql:8
   user: mysql
   environment:
    - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    - MYSQL_DATABASE=${MYSQL_DATABASE}
    - MYSQL_USER=${MYSQL_USER}
    - MYSQL_PASSWORD=${MYSQL_PASSWORD}
   env_file:
    - ./env/mysql.env
   command: --init-file /data/application/init.sql
   volumes:
        - ./src/init.sql:/data/application/init.sql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    env_file:
    - ./env/phpmyadmin.env
    ports:
      - 8081:80
  